# This file was generated by GoReleaser. DO NOT EDIT.
cask "n2k" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "a3adcfc08bfaa4aac252bd2f225574afb5827884a90c75a2c219202d9f2c97dc"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "31f8447cf5f7162cf65ef8b1c32c36e1c3778e0222874f1e34d1b2fd857b771f"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "0aa9acad228b888d448609133a8846ad6ce2f570c3a6400147df0c78fccdcd85"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "7e61afccc272adb6073bbd8def71161598bb5e032f31a91965447e932d4b9289"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  name "n2k"
  desc "NMEA 2000 capture, diagnostics, and schema tools"
  homepage "https://github.com/open-ships/n2k-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n2k"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n2k"]
    end
  end

  # No zap stanza required

end
