# This file was generated by GoReleaser. DO NOT EDIT.
cask "n2k" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "547b9991efc2fe798c493ff597228d478989ae0afebfb5877ca61c5de78bf886"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "75303c49f8c2db9b8825b7165dc57baef9bea39d2eb15dff9bbff2307ff14ff1"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "400155e23d1345a7b8d10948699e0c25f5d0210ec0d0456bf0569d5d450bb3db"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "70cf90a5589ca65c339e50107dc040fddc5a90a783d088a8582011121d5f6ce1"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  name "n2k"
  desc "NMEA 2000 capture, diagnostics, and schema tools"
  homepage "https://github.com/open-ships/n2k-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n2k"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n2k"]
    end
  end

  # No zap stanza required

end
