# This file was generated by GoReleaser. DO NOT EDIT.
cask "n2k" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "0f8a6b4bdb970b0ac06feaaaf44630b7dd37bba2535a08b3ab9ae00d4096cd05"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "9a15a648e84ce974a0539e1bbbf3ab11913d5b40b8a17bad33842698e512ad75"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbc6b11eac3812e82b03f30a9161dc82798feb5d75b979eedb05021b9a420198"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_amd64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
    on_arm do
      sha256 "ff736002df75496e3d8b7a5d57303002c7b21d9b48573c303950db3a0534d8cc"
      url "https://github.com/open-ships/n2k-cli/releases/download/v#{version}/n2k_#{version}_linux_arm64.tar.gz",
        verified: "github.com/open-ships/n2k-cli/"
    end
  end

  name "n2k"
  desc "NMEA 2000 capture, diagnostics, and schema tools"
  homepage "https://github.com/open-ships/n2k-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "n2k"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/n2k"]
    end
  end

  # No zap stanza required

end
